# Solve Ax = B and find (x, y) coordinates in Python

In [1]:
# import the liberary
import numpy as np

### Sove this system of equations using python:

2x + 6y = 10

8x- 6y = 3

In [3]:
# Create co-efficient matrix A
A = np.array([[2, 6], [8, -6]]) # This is 2x2 matrix
A

array([[ 2,  6],
       [ 8, -6]])

In [4]:
B = np.array([10, 3]) # This a vector
B

array([10,  3])

In [6]:
# Let's Solve Ax = B
np.linalg.solve(A, B)

array([1.3       , 1.23333333])