# Solving System of Complex Equations in Python

### Solve this complex system of equations:

                                                             (1+2i)x + (2-i)y = 4 + i

                                                                 (3-i)x + 4y = 3 + 4i

In [1]:
# import the liberary
import numpy as np

In [2]:
# Coefficients matrix A with complex numbers
A_complex = np.array([[1+2j, 2-1j], [3-1j, 4]])
A_complex

array([[1.+2.j, 2.-1.j],
       [3.-1.j, 4.+0.j]])

In [3]:
# Constants matrix B with complex numbers
B_complex = np.array([4+1j, 3+4j])
B_complex

array([4.+1.j, 3.+4.j])

In [4]:
# Solving for X in the complex case
X_complex = np.linalg.solve(A_complex, B_complex)
X_complex

array([-0.11176471-0.45294118j,  0.94705882+1.31176471j])