# Singular Value Decomposition (SVD) in Python

In [2]:
# import the liberary
import numpy as np

In [3]:
# Let's generate a random  matrix of 4x5
A = np.random.rand(4, 5)
A

array([[0.74708256, 0.97718051, 0.64150624, 0.74662829, 0.15473255],
       [0.53468929, 0.10143473, 0.11367652, 0.23110265, 0.74243312],
       [0.71654159, 0.18461437, 0.85634322, 0.90539972, 0.80797564],
       [0.87776235, 0.77615387, 0.83541796, 0.14081701, 0.91468695]])

In [5]:
# Let's apply SVD here
U, Sigma, VT = np.linalg.svd(A)

In [12]:
# Print each matrix separately
print("U Matrix=", U)
print("--------------------------------")
print("Sigma Matrix=",Sigma)
print("--------------------------------")
print("VT Matrix=",VT) # here T stands for transpose

U Matrix= [[ 0.51129821  0.7857731   0.08235199  0.33816111]
 [ 0.28675683 -0.52182063 -0.08283001  0.79913262]
 [ 0.56038704 -0.29889982  0.70137764 -0.32356556]
 [ 0.58507353 -0.14464704 -0.70315485 -0.37727901]]
--------------------------------
Sigma Matrix= [2.78673331 0.86326707 0.69378746 0.3284871 ]
--------------------------------
VT Matrix= [[ 0.52046743  0.38980419  0.47699688  0.3724011   0.45930138]
 [-0.0383594   0.63417438  0.07872189  0.20282681 -0.74095584]
 [-0.14039054 -0.49611887  0.08158878  0.8336199  -0.18049292]
 [ 0.35591178  0.17943727 -0.86607284  0.27726766  0.11903595]
 [-0.76240378  0.40932125 -0.09766243  0.21995274  0.43963557]]


In [9]:
U.shape

(4, 4)

In [10]:
Sigma.shape

(4,)

In [11]:
VT.shape

(5, 5)