## numpy (Part 03)

In [1]:
# import liberary
import numpy as np

## Indexing and Slicing

In [5]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
# we want the value at index 4
a[4]

4

In [8]:
a[0]

0

In [10]:
a[-1] # from right to left we use negative sign 

8

In [15]:
a[2:] # gives value from index 2 to onward

array([2, 3, 4, 5, 6, 7, 8])

In [16]:
a[2:6] # gives values between from index 2 to 6

array([2, 3, 4, 5])

In [21]:
# creating 2D array
b = np.array([[1, 2, 3, 4], [5, 5, 6, 7], [8, 9, 10, 11]])
b

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b[0]

array([1, 2, 3, 4])

In [23]:
b[0][2]

3

In [24]:
b

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [27]:
b

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b[b < 10]

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [31]:
b[b >= 5]

array([ 5,  5,  6,  7,  8,  9, 10, 11])

In [38]:
b

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
b[(b < 9) & (b > 4)] 

array([5, 5, 6, 7, 8])

In [40]:
b[(b < 9) | (b > 4)] 

array([ 1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 10, 11])

## filtration

In [32]:
b

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
# filtering even values

In [35]:
b[b % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [36]:
# filtering odd values

In [37]:
b[b % 2 == 1]

array([ 1,  3,  5,  5,  7,  9, 11])

In [43]:
b[((b > 1) & (b < 9)) & (b % 2 == 0)] 

array([2, 4, 6, 8])

## Making an array from a data or another array

In [44]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
new_a = a[2:6]
new_a

array([2, 3, 4, 5])

In [53]:
b

array([[ 1,  2,  3,  4],
       [ 5,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
new_b = b[2:, 1:]
new_b

array([[ 9, 10, 11]])

## Concatination can also be done my stacking

In [63]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [64]:
d = np.arange(7, 13)
d

array([ 7,  8,  9, 10, 11, 12])

In [69]:
ver_stack = np.vstack((c, d))
ver_stack

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12]])

In [70]:
hor_stack = np.hstack((c, d))
hor_stack

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12])