## numpy (Part 02)

In [2]:
# import the liberary
import numpy as np

## Empty arrays

In [5]:
empty = np.empty(4) # these values are not really zero but these are close to zero we can see by looking at their powers
empty

array([0.00000000e+000, 1.07710862e-311, 1.07710862e-311, 1.07710862e-311])

In [8]:
empty[1] # we can see the individual index of the array by using this technique

1.0771086205735e-311

In [12]:
empty2 = np.empty((4, 3)) 
empty2

array([[1.07710994e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.16709769e-312, 6.45841997e+170],
       [9.76876013e+165, 5.05921750e-038, 1.55973375e+161],
       [6.09658570e+170, 2.14359928e+160, 4.46589463e-033]])

In [13]:
empty2[1]

array([0.00000000e+000, 1.16709769e-312, 6.45841997e+170])

In [15]:
empty2[1][2] 

6.458419966397617e+170

## Even and Odd numbers from an array

In [17]:
# generating an array from (0 - 24)
x = np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
# generating an even numbers array
even = np.arange(0, 20, 2) # (start = 0, end = 20, difference between the numbers = 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
# generating odd numbers array
odd = np.arange(1, 20, 2) # (start = 1, end = 20, difference between the numbers = 1)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Generating an array with manual difference

In [41]:
difference = np.arange (1, 20, 3)
difference

array([ 1,  4,  7, 10, 13, 16, 19])

In [42]:
diff = np.arange(6, 30, 0.4)
diff

array([ 6. ,  6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. ,
       10.4, 10.8, 11.2, 11.6, 12. , 12.4, 12.8, 13.2, 13.6, 14. , 14.4,
       14.8, 15.2, 15.6, 16. , 16.4, 16.8, 17.2, 17.6, 18. , 18.4, 18.8,
       19.2, 19.6, 20. , 20.4, 20.8, 21.2, 21.6, 22. , 22.4, 22.8, 23.2,
       23.6, 24. , 24.4, 24.8, 25.2, 25.6, 26. , 26.4, 26.8, 27.2, 27.6,
       28. , 28.4, 28.8, 29.2, 29.6])

## linspace() is used to set linear trends between the numbers

In [49]:
lin = np.linspace(0, 10, num = 5) # how many numbers you want between 0 and 10 that have equal distance
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
lin = np.linspace(0, 20, num = 10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## We can generate an array with specifying its dtype

In [52]:
x = np.arange(0, 10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x.dtype

dtype('int32')

In [54]:
x = np.arange(0, 10, dtype = np.float64)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
x.dtype

dtype('float64')

In [59]:
y = np.arange(0, 50, 1.3)
y

array([ 0. ,  1.3,  2.6,  3.9,  5.2,  6.5,  7.8,  9.1, 10.4, 11.7, 13. ,
       14.3, 15.6, 16.9, 18.2, 19.5, 20.8, 22.1, 23.4, 24.7, 26. , 27.3,
       28.6, 29.9, 31.2, 32.5, 33.8, 35.1, 36.4, 37.7, 39. , 40.3, 41.6,
       42.9, 44.2, 45.5, 46.8, 48.1, 49.4])

In [60]:
y.dtype

dtype('float64')

In [61]:
y = np.arange(0, 50, 1.3, dtype = np.int32)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38])

In [62]:
y.dtype

dtype('int32')

## Sorting arrays

In [63]:
arr = np.array([5, 84, 632, 63, 20, 1, 8, 7, 45, 11])
arr

array([  5,  84, 632,  63,  20,   1,   8,   7,  45,  11])

In [66]:
arr = np.sort(arr) 
arr

array([  1,   5,   7,   8,  11,  20,  45,  63,  84, 632])

## Concatination

## concatinate 1D arrays

In [67]:
x = np.array([1, 2, 3, 4, 5, 6])
x

array([1, 2, 3, 4, 5, 6])

In [68]:
y = np.array([7, 8, 9, 10, 11, 12, 13])
y

array([ 7,  8,  9, 10, 11, 12, 13])

In [69]:
z = np.concatenate((x, y))
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

## concatinate 2D arrays

In [76]:
x2 = np.array([[1, 2], [3, 4]])
x2

array([[1, 2],
       [3, 4]])

In [77]:
y2 = np.array([[5, 6], [7, 8]])

In [78]:
y2

array([[5, 6],
       [7, 8]])

In [79]:
z2 = np.concatenate((x2, y2))
z2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
# now, concatinate along row (axis = 0)
z2 = np.concatenate((x2, y2), axis = 0)
z2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [81]:
# now, concatinate along column (axis = 1)
z2 = np.concatenate((x2, y2), axis = 1)
z2

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Creating 3D array ( for a 3D array there should be 3 2D arrays)

In [82]:
three_d_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
three_d_array

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [83]:
three_d_array.ndim

3

In [92]:
three_d_array.shape

(3, 2, 4)

In [84]:
len(three_d_array) # len(): This function returns the number of elements in an array or list

3

In [94]:
three_d_array.size # .size: This function returns the total number of elements in the array

24

## Reshaping arrays

In [87]:
three_d_array

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [90]:
three_d_array.reshape(8, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 0, 1],
       [2, 3, 4],
       [5, 6, 7]])

In [91]:
three_d_array.reshape(3, 8)

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [93]:
three_d_array.reshape(4, 2, 3)

array([[[0, 1, 2],
        [3, 4, 5]],

       [[6, 7, 0],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 0, 1]],

       [[2, 3, 4],
        [5, 6, 7]]])